runtime: custom
env: flex
module: otp
api_version: 1
manual_scaling:
 instances: 1
handlers:
 - url: /.*
   script: none
resources:
 cpu: 2
 memory_gb: 8
 disk_size_gb: 10
env_variables:
 JAVA_HEAP_OPTS: -Xms256m -Xmx512m